deploy:
  stage: deploy
  image: debian:10
  only:
    - master
  script:
    - apt-get update -qq
    - apt-get install -y -qq git
    - git archive -o starting-point-deck.zip HEAD
    - mv starting-point-deck.zip /artefacts/