name: CI
on:
  push:

jobs:
  test-build:
    runs-on: ubuntu-latest
    container:
      image: node:10.12
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g gulp
      - run: npm install yarn
      - run: yarn
      - run: gulp build

  release:
    runs-on: ubuntu-latest
    needs: test-build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: git archive -o starting-point-deck.zip HEAD
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest starting-point deck"
          files: starting-point-deck.zip
